version: '3.8'

services:
  url_shortener_postgres:
    image: postgres:alpine
    container_name: url_shortener_postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - url_shortener_postgres_data:/var/lib/postgresql/data

  url_shortener_redis:
    image: redis:alpine
    container_name: url_shortener_redis
    ports:
      - '6379:6379'
    volumes:
      - url_shortener_redis_data:/data # Needs updating

networks:
  default:
    name: url_shortener # Needs updating

volumes:
  url_shortener_postgres_data: # Needs updating
  url_shortener_redis_data: # Needs updating
